TRI_LAYER_ENABLE = yes

MOUSEKEY_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = ssd1306
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
VIA_ENABLE = yes
LTO_ENABLE = yes
RGBLIGHT_ENABLE = yes
# RGBLIGHT_DRIVER = apa102
ENCODER_MAP_ENABLE = yes
WPM_ENABLE = yes
MIDI_ENABLE = no
SLEEP_LED_ENABLE = no
